export interface Place {
  id: string
  name: string
  type: "rooftop" | "club" | "cafe" | "restaurant" | "lounge" | "bar" | "bistro"
  distance: string
  distanceKm: number
  weightedRating: number
  reviewCount: number
  vibeTag: string
  videoThumbnail: string
  isLiked: boolean
  isBookmarked: boolean
  likeCount: number
  commentCount: number
  shareCount: number
  description: string
  crowdLevel: number
  liveStatus: "Packed" | "Busy" | "Moderate" | "Quiet"
  trendPercent: string
  mapX: number
  mapY: number
  category: string
  uploader?: {
    name: string
    handle?: string
    avatar: string
  }
  caption?: string
  isVerified?: boolean
  isBusiness?: boolean
  promoBadge?: string
  loyaltyReward?: string
  eventDateTime?: string
  visited?: boolean
}

export const mockPlaces: Place[] = [
  {
    id: "chill-vibes-feed",
    uploader: { name: "Chill Vibes", handle: "@chill_vibes", avatar: "https://i.pravatar.cc/150?u=3" },
    caption: "Late-night bites, loud music, and the best rooftop energy in the city.",
    visited: false,
    name: "Cangi Cafe & Restaurant",
    type: "cafe",
    distance: "2.4 km away",
    distanceKm: 2.4,
    weightedRating: 4.8,
    reviewCount: 1247,
    vibeTag: "Energetic",
    videoThumbnail: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&h=1200&fit=crop",
    isLiked: false,
    isBookmarked: false,
    likeCount: 12400,
    commentCount: 892,
    shareCount: 341,
    description: "The trendiest spot in Baku with craft cocktails and DJ sets every weekend.",
    crowdLevel: 85,
    liveStatus: "Busy",
    trendPercent: "+24%",
    mapX: 35,
    mapY: 25,
    category: "Cafe & Restaurant",
  },
  {
    id: "flame-tower-sky-bar",
    uploader: { name: "Flame Tower Sky Bar", avatar: "https://i.pravatar.cc/150?u=11" },
    caption: "Elevated cocktails, skyline sunsets, and a loyalty offer that keeps guests coming back.",
    visited: true,
    name: "Flame Tower Sky Bar",
    type: "rooftop",
    distance: "1.5 km away",
    distanceKm: 1.5,
    weightedRating: 4.9,
    reviewCount: 2890,
    vibeTag: "Sponsored",
    videoThumbnail: "https://images.unsplash.com/photo-1470337458703-46ad1756a187?w=800&h=1200&fit=crop",
    isLiked: false,
    isBookmarked: false,
    likeCount: 51200,
    commentCount: 3100,
    shareCount: 1890,
    description: "Iconic rooftop bar at Flame Towers with 360° views of Baku and the Caspian Sea.",
    crowdLevel: 88,
    liveStatus: "Packed",
    trendPercent: "+27%",
    mapX: 55,
    mapY: 20,
    category: "Rooftop Bar",
    isBusiness: true,
    isVerified: true,
    promoBadge: "Sponsored",
    loyaltyReward: "Loyalty: Get 20% Cashback on your 5th visit",
  },
  {
    id: "neon-nights-club",
    uploader: { name: "Neon Nights Club", avatar: "https://i.pravatar.cc/150?u=21" },
    caption: "🔥 Special Guest DJ Set! Early bird tickets available now.",
    visited: true,
    name: "Neon Nights Club",
    type: "club",
    distance: "3.1 km away",
    distanceKm: 3.1,
    weightedRating: 4.6,
    reviewCount: 3412,
    vibeTag: "Upcoming Event",
    videoThumbnail: "https://images.unsplash.com/photo-1545128485-c400e7702796?w=800&h=1200&fit=crop",
    isLiked: false,
    isBookmarked: false,
    likeCount: 45200,
    commentCount: 2800,
    shareCount: 1230,
    description: "Baku's ultimate nightlife destination with world-class DJs and immersive light shows.",
    crowdLevel: 92,
    liveStatus: "Packed",
    trendPercent: "+31%",
    mapX: 25,
    mapY: 60,
    category: "Nightclub",
    isBusiness: true,
    isVerified: true,
    promoBadge: "Upcoming Event",
    eventDateTime: "This Friday, 11:00 PM",
  },
  {
    id: "old-city-bistro",
    uploader: { name: "Old City Bites", handle: "@oldcitybites", avatar: "https://i.pravatar.cc/150?u=31" },
    caption: "Warm plates, late dinners, and a calm spot in the old quarter.",
    visited: false,
    name: "Old City Bistro",
    type: "bistro",
    distance: "1.8 km away",
    distanceKm: 1.8,
    weightedRating: 4.7,
    reviewCount: 982,
    vibeTag: "Cozy",
    videoThumbnail: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&h=1200&fit=crop",
    isLiked: false,
    isBookmarked: true,
    likeCount: 8200,
    commentCount: 430,
    shareCount: 140,
    description: "Classic European comfort food inside the old city walls.",
    crowdLevel: 58,
    liveStatus: "Moderate",
    trendPercent: "+18%",
    mapX: 16,
    mapY: 34,
    category: "Bistro",
  },
  {
    id: "harbor-lounge",
    uploader: { name: "Harbor Lounge", avatar: "https://i.pravatar.cc/150?u=32" },
    caption: "Sea views, quiet conversations, and perfect sunset seating.",
    visited: false,
    name: "Harbor Lounge",
    type: "lounge",
    distance: "3.8 km away",
    distanceKm: 3.8,
    weightedRating: 4.5,
    reviewCount: 653,
    vibeTag: "Relaxed",
    videoThumbnail: "https://images.unsplash.com/photo-1514933651103-005eec06c04b?w=800&h=1200&fit=crop",
    isLiked: false,
    isBookmarked: false,
    likeCount: 5400,
    commentCount: 214,
    shareCount: 88,
    description: "A polished lounge near the promenade for slow evenings.",
    crowdLevel: 42,
    liveStatus: "Quiet",
    trendPercent: "+14%",
    mapX: 78,
    mapY: 30,
    category: "Lounge",
  },
  {
    id: "neon-garden",
    uploader: { name: "Neon Garden", handle: "@neongarden", avatar: "https://i.pravatar.cc/150?u=33" },
    caption: "Daylight brunch turns into DJ sets after 8 PM.",
    visited: true,
    name: "Neon Garden",
    type: "cafe",
    distance: "2.1 km away",
    distanceKm: 2.1,
    weightedRating: 4.6,
    reviewCount: 744,
    vibeTag: "Brunch",
    videoThumbnail: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&h=1200&fit=crop",
    isLiked: false,
    isBookmarked: false,
    likeCount: 9300,
    commentCount: 503,
    shareCount: 211,
    description: "Open-air café with plant-filled patios and a late-day crowd.",
    crowdLevel: 63,
    liveStatus: "Busy",
    trendPercent: "+19%",
    mapX: 22,
    mapY: 54,
    category: "Café",
  },
  {
    id: "caspian-kitchen",
    uploader: { name: "Caspian Kitchen", avatar: "https://i.pravatar.cc/150?u=34" },
    caption: "Big tables, group dinners, and fresh seafood every evening.",
    visited: false,
    name: "Caspian Kitchen",
    type: "restaurant",
    distance: "4.0 km away",
    distanceKm: 4.0,
    weightedRating: 4.8,
    reviewCount: 1102,
    vibeTag: "Family",
    videoThumbnail: "https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800&h=1200&fit=crop",
    isLiked: false,
    isBookmarked: false,
    likeCount: 7600,
    commentCount: 361,
    shareCount: 122,
    description: "Modern seafood restaurant with roomy tables and warm service.",
    crowdLevel: 70,
    liveStatus: "Busy",
    trendPercent: "+12%",
    mapX: 44,
    mapY: 18,
    category: "Restaurant",
  },
  {
    id: "sunset-terrace",
    uploader: { name: "Sunset Terrace", avatar: "https://i.pravatar.cc/150?u=35" },
    caption: "Golden hour views with a soft house playlist.",
    visited: false,
    name: "Sunset Terrace",
    type: "rooftop",
    distance: "2.9 km away",
    distanceKm: 2.9,
    weightedRating: 4.9,
    reviewCount: 1310,
    vibeTag: "Sunset",
    videoThumbnail: "https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=800&h=1200&fit=crop",
    isLiked: false,
    isBookmarked: true,
    likeCount: 16300,
    commentCount: 801,
    shareCount: 307,
    description: "Rooftop dining with sunset seating and skyline views.",
    crowdLevel: 81,
    liveStatus: "Packed",
    trendPercent: "+23%",
    mapX: 68,
    mapY: 46,
    category: "Rooftop",
  },
  {
    id: "district-brew",
    uploader: { name: "District Brew", avatar: "https://i.pravatar.cc/150?u=36" },
    caption: "Coffee, laptop tables, and a strong afternoon crowd.",
    visited: false,
    name: "District Brew",
    type: "cafe",
    distance: "1.2 km away",
    distanceKm: 1.2,
    weightedRating: 4.4,
    reviewCount: 540,
    vibeTag: "Work",
    videoThumbnail: "https://images.unsplash.com/photo-1498804103079-a6351b050096?w=800&h=1200&fit=crop",
    isLiked: false,
    isBookmarked: false,
    likeCount: 4300,
    commentCount: 161,
    shareCount: 59,
    description: "Fast coffee and a solid daytime work setup.",
    crowdLevel: 51,
    liveStatus: "Moderate",
    trendPercent: "+11%",
    mapX: 33,
    mapY: 72,
    category: "Café",
  },
  {
    id: "midtown-nerve",
    uploader: { name: "Midtown Nerve", avatar: "https://i.pravatar.cc/150?u=37" },
    caption: "Live bands, strong cocktails, and a dance floor that fills fast.",
    visited: false,
    name: "Midtown Nerve",
    type: "bar",
    distance: "3.3 km away",
    distanceKm: 3.3,
    weightedRating: 4.5,
    reviewCount: 880,
    vibeTag: "Live Music",
    videoThumbnail: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=800&h=1200&fit=crop",
    isLiked: false,
    isBookmarked: false,
    likeCount: 9800,
    commentCount: 702,
    shareCount: 174,
    description: "Bar and live music venue with a night-forward crowd.",
    crowdLevel: 77,
    liveStatus: "Busy",
    trendPercent: "+21%",
    mapX: 54,
    mapY: 70,
    category: "Bar",
  },
  {
    id: "northshore-kitchen",
    uploader: { name: "Northshore Kitchen", avatar: "https://i.pravatar.cc/150?u=38" },
    caption: "Open kitchen, all-day brunch, and a polished lunch crowd.",
    visited: false,
    name: "Northshore Kitchen",
    type: "restaurant",
    distance: "5.2 km away",
    distanceKm: 5.2,
    weightedRating: 4.6,
    reviewCount: 770,
    vibeTag: "Brunch",
    videoThumbnail: "https://images.unsplash.com/photo-1466978913421-dad2ebd01d17?w=800&h=1200&fit=crop",
    isLiked: false,
    isBookmarked: false,
    likeCount: 5100,
    commentCount: 248,
    shareCount: 91,
    description: "Bright dining room with a dependable all-day menu.",
    crowdLevel: 54,
    liveStatus: "Moderate",
    trendPercent: "+15%",
    mapX: 81,
    mapY: 64,
    category: "Restaurant",
  },
  {
    id: "copper-arcade",
    uploader: { name: "Copper Arcade", avatar: "https://i.pravatar.cc/150?u=39" },
    caption: "Arcade nights, neon lights, and a younger crowd after 9 PM.",
    visited: false,
    name: "Copper Arcade",
    type: "club",
    distance: "2.6 km away",
    distanceKm: 2.6,
    weightedRating: 4.3,
    reviewCount: 690,
    vibeTag: "Nightlife",
    videoThumbnail: "https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=800&h=1200&fit=crop",
    isLiked: false,
    isBookmarked: false,
    likeCount: 6400,
    commentCount: 331,
    shareCount: 133,
    description: "Compact club room with arcade machines and DJ nights.",
    crowdLevel: 89,
    liveStatus: "Packed",
    trendPercent: "+26%",
    mapX: 62,
    mapY: 14,
    category: "Club",
  },
  {
    id: "glasshouse-cafe",
    uploader: { name: "Glasshouse Cafe", avatar: "https://i.pravatar.cc/150?u=40" },
    caption: "Soft lighting, quieter corners, and excellent desserts.",
    visited: false,
    name: "Glasshouse Cafe",
    type: "cafe",
    distance: "0.9 km away",
    distanceKm: 0.9,
    weightedRating: 4.7,
    reviewCount: 488,
    vibeTag: "Calm",
    videoThumbnail: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&h=1200&fit=crop",
    isLiked: false,
    isBookmarked: false,
    likeCount: 3900,
    commentCount: 144,
    shareCount: 52,
    description: "Quiet glass-front café for meetings and dessert breaks.",
    crowdLevel: 38,
    liveStatus: "Quiet",
    trendPercent: "+9%",
    mapX: 13,
    mapY: 78,
    category: "Café",
  },
  {
    id: "harvest-bistro",
    uploader: { name: "Harvest Bistro", avatar: "https://i.pravatar.cc/150?u=41" },
    caption: "Neighborhood comfort food with a calm local crowd.",
    visited: false,
    name: "Harvest Bistro",
    type: "bistro",
    distance: "4.8 km away",
    distanceKm: 4.8,
    weightedRating: 4.6,
    reviewCount: 705,
    vibeTag: "Local Favorite",
    videoThumbnail: "https://images.unsplash.com/photo-1470337458703-46ad1756a187?w=800&h=1200&fit=crop",
    isLiked: false,
    isBookmarked: false,
    likeCount: 4700,
    commentCount: 202,
    shareCount: 72,
    description: "Slow evenings, great bread, and a relaxed dining room.",
    crowdLevel: 46,
    liveStatus: "Moderate",
    trendPercent: "+13%",
    mapX: 87,
    mapY: 18,
    category: "Bistro",
  },
  {
    id: "moonrise-rooftop",
    uploader: { name: "Moonrise Rooftop", avatar: "https://i.pravatar.cc/150?u=42" },
    caption: "A late-night rooftop with a strong after-dark surge.",
    visited: false,
    name: "Moonrise Rooftop",
    type: "rooftop",
    distance: "2.2 km away",
    distanceKm: 2.2,
    weightedRating: 4.8,
    reviewCount: 1198,
    vibeTag: "Late Night",
    videoThumbnail: "https://images.unsplash.com/photo-1505236858219-8359eb29e329?w=800&h=1200&fit=crop",
    isLiked: false,
    isBookmarked: true,
    likeCount: 11800,
    commentCount: 522,
    shareCount: 241,
    description: "High energy rooftop with views and a packed weekend schedule.",
    crowdLevel: 84,
    liveStatus: "Busy",
    trendPercent: "+22%",
    mapX: 73,
    mapY: 84,
    category: "Rooftop",
  },
  {
    id: "ember-room",
    uploader: { name: "Ember Room", avatar: "https://i.pravatar.cc/150?u=43" },
    caption: "Cocktail-forward, moody, and best after 10 PM.",
    visited: false,
    name: "Ember Room",
    type: "lounge",
    distance: "3.9 km away",
    distanceKm: 3.9,
    weightedRating: 4.7,
    reviewCount: 912,
    vibeTag: "Cocktails",
    videoThumbnail: "https://images.unsplash.com/photo-1514933651103-005eec06c04b?w=800&h=1200&fit=crop",
    isLiked: false,
    isBookmarked: false,
    likeCount: 6900,
    commentCount: 280,
    shareCount: 104,
    description: "Low-light lounge with a cocktail list and cozy seating.",
    crowdLevel: 64,
    liveStatus: "Busy",
    trendPercent: "+16%",
    mapX: 48,
    mapY: 92,
    category: "Lounge",
  },
]

export function formatCount(count: number): string {
  if (count >= 1000) {
    return (count / 1000).toFixed(1).replace(/\.0$/, "") + "K"
  }
  return count.toString()
}
